ALTER TABLE PRODUCT
    ADD COLUMN isGift BOOLEAN NOT NULL DEFAULT FALSE;
# this table used to exist with a different structure
DROP TABLE IF EXISTS GIFT_CODE;

CREATE TABLE GIFT_CODE
(
    code       VARCHAR(255) PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    product_id VARCHAR(255) NOT NULL,
    use_count  INT DEFAULT 1,
    beginTime  TIMESTAMP    NOT NULL,
    endTime    TIMESTAMP    NOT NULL,
    CONSTRAINT FK_GIFT_CODE_PRODUCT_product_id FOREIGN KEY (product_id) REFERENCES PRODUCT (productId) ON DELETE CASCADE
) COLLATE = utf8mb4_unicode_ci;

CREATE TABLE PERSONA_GIFT
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT,
    persona_id BIGINT       NOT NULL,
    code       VARCHAR(255) NOT NULL,
    use_count  INT          NOT NULL,
    CONSTRAINT FK_PERSONA_GIFT_PERSONA_persona_id FOREIGN KEY (persona_id) REFERENCES PERSONA (ID) ON DELETE CASCADE,
    CONSTRAINT FK_PERSONA_GIFT_GIFT_CODE_code FOREIGN KEY (code) REFERENCES GIFT_CODE (code) ON DELETE CASCADE,
    CONSTRAINT UK_PERSONA_ID_CODE UNIQUE KEY (persona_id, code)
) COLLATE = utf8mb4_unicode_ci;